# Generated by Django 3.2.4 on 2021-11-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WAMG', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='things',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Put name from your thing', max_length=15)),
                ('sku', models.IntegerField(help_text='Put sku your thing')),
                ('ean', models.IntegerField(blank=True, help_text='Put ean your thing')),
                ('color', models.CharField(blank=True, help_text='Put color your thing', max_length=10)),
                ('note', models.CharField(blank=True, help_text='You can describe your thing here...', max_length=200)),
                ('date_add', models.DateField()),
                ('user', models.CharField(max_length=50)),
            ],
        ),
    ]
