# Generated by Django 3.2.4 on 2021-11-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WAMG', '0002_things'),
    ]

    operations = [
        migrations.AlterField(
            model_name='things',
            name='sku',
            field=models.CharField(help_text='Put sku your thing', max_length=30),
        ),
    ]
