# Generated by Django 3.2.4 on 2021-11-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WAMG', '0003_alter_things_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='things',
            name='ean',
            field=models.CharField(blank=True, help_text='Put ean your thing', max_length=30),
        ),
    ]
