# Generated by Django 3.2.4 on 2021-11-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WAMG', '0005_things_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='things',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='things',
            name='place',
            field=models.CharField(choices=[('1', '🚗'), ('2', 'Room'), ('3', 'Garage'), ('4', 'Garden'), ('5', 'Basement'), ('6', 'Terrace'), ('7', 'Attic'), ('8', 'Bathroom'), ('9', 'Kitchen'), ('10', 'Barn'), ('11', 'Semitrailer'), ('12', 'Owned by Friend'), ('13', 'Owned by Family'), ('14', 'Summer house')], default='Room', max_length=30),
        ),
    ]
