# Generated by Django 3.2.4 on 2021-11-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WAMG', '0006_auto_20211113_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='things',
            name='color',
            field=models.CharField(blank=True, choices=[('1', '🔴'), ('2', ''), ('3', ''), ('4', ''), ('5', ''), ('6', ''), ('7', ''), ('8', ''), ('9', ''), ('10', ''), ('11', ''), ('12', ''), ('13', '  '), ('14', ''), ('15', '')], default='Brak', max_length=30),
        ),
        migrations.AlterField(
            model_name='things',
            name='place',
            field=models.CharField(choices=[('1', '🚗 - Car'), ('2', '🏠 - Room'), ('3', '🔧 - Garage'), ('4', '🍅 - Garden'), ('5', '🛄 - Basement'), ('6', '🧹 - Terrace'), ('7', '👻 - Attic'), ('8', '🛀 - Bathroom'), ('9', '🍽️ - Kitchen'), ('10', '🐴 - Barn'), ('11', '🚛 - Semitrailer'), ('12', '🧔 - Owned by Friend'), ('13', '👪 - Owned by Family'), ('14', '⛺ - Summer house'), ('15', '❔ - Other')], default='2', max_length=30),
        ),
        migrations.AlterField(
            model_name='things',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
