# Generated by Django 3.2.4 on 2021-11-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WAMG', '0007_auto_20211113_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='things',
            name='color',
            field=models.CharField(blank=True, choices=[('1', '🔴'), ('2', '🟠'), ('3', '🟡'), ('4', '🟢'), ('5', '🔵'), ('6', '🟣'), ('7', '🟤'), ('8', '⚫'), ('9', '⚪')], default='Brak', max_length=30),
        ),
    ]
