# Generated by Django 3.2.4 on 2021-11-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WAMG', '0008_alter_things_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='things',
            name='name',
            field=models.CharField(help_text='Put name from your thing', max_length=100),
        ),
        migrations.AlterField(
            model_name='things',
            name='user',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
