# Generated by Django 3.2.4 on 2021-11-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WAMG', '0012_alter_things_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='things',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/<django.db.models.fields.CharField>/'),
        ),
    ]
