# Generated by Django 3.2.4 on 2021-11-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WAMG', '0013_alter_things_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='things',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/<django.db.models.query_utils.DeferredAttribute object at 0x0000011850ACD9D0>/'),
        ),
    ]
