# Generated by Django 3.2.4 on 2021-11-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WAMG', '0014_alter_things_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='things',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='things',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
