# Generated by Django 3.2.4 on 2021-11-17 20:17

import WAMG.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WAMG', '0018_alter_things_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='things',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=WAMG.models.things.upload_path),
        ),
    ]
