# Generated by Django 3.2.4 on 2022-02-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WAMG', '0019_alter_things_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='things',
            name='color',
            field=models.CharField(blank=True, choices=[('1', '🔴'), ('2', '🟠'), ('3', '🟡'), ('4', '🟢'), ('5', '🔵'), ('6', '🟣'), ('7', '🟤'), ('8', '⚫'), ('9', '⚪')], default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='things',
            name='ean',
            field=models.CharField(blank=True, default='-', help_text='Put ean your thing', max_length=30),
        ),
        migrations.AlterField(
            model_name='things',
            name='note',
            field=models.CharField(blank=True, default='-', help_text='You can describe your thing here...', max_length=200),
        ),
        migrations.AlterField(
            model_name='things',
            name='sku',
            field=models.CharField(default='-', help_text='Put sku your thing', max_length=30),
        ),
    ]
